# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'WXGZDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for WXGZDemo
  pod 'MTSSSDK', '~> 1.2.0.2'

end
